import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import { Formik, Form, Field, ErrorMessage } from "formik";
import Link from "next/link";
import { Router } from "next/router";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImthbWFhbEBleGFtcGxlLmNvbSIsIkZpcnN0X25hbWUiOiJLYWFsYSIsIkxhc3RfbmFtZSI6Ik1hYWthIiwiVWlkIjoiNjM5NzA5MmNhYjgwYmNiNDE1NzUyMDU2IiwiZXhwIjoxNjcwOTI5MTA0fQ.s_c9GPwC7BSEMie8MXNrE_zPUJcrNiUQ42d_D3D5-W4";

  if (typeof window !== "undefined") {
    // Perform localStorage action
    localStorage.setItem("token", JSON.stringify(token));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* goole fonts inter & roboto */}
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <div>
        <div className="columns-1 md:columns-2 gap-[10px] align-middle md:flex block inter">
          <div>
            <div className="hidden md:block">
              <Image
                src={"/logo-medium.png"}
                width={219}
                height={80}
                alt="medium-logo"
              ></Image>
            </div>
            <div className="block md:hidden">
              <Image
                src={"/logo-small.png"}
                width={104}
                height={38}
                alt="small-logo"
              ></Image>
            </div>
            <div className="mb-[20px]">
              <Image
                className="w-10/12 md:w-full mx-auto"
                src={"/istockphoto-1321277096-612x612 1.png"}
                width={612}
                height={437}
                alt="main-image"
              ></Image>
            </div>
          </div>
          <div className="w-12/12 mobile:w-10/12 md:w-8/12 lg:w-5/12 mx-auto md:ml-auto pt-[30px] md:pt-0 min-h-[480px] md:h-[calc(100vh-40px)] flex align-middle justify-center flex-col shadow-xl">
            <Formik
              initialValues={{
                email: "",
                password: "",
              }}
              validate={(values) => {
                const errors = {};
                if (values.email == "") {
                  errors.email = "please enter valid email";
                }
                if (values.password == "") {
                  errors.password = "password requires at least 8 characters";
                }
                return errors;
              }}
              onSubmit={async (values) => {
                let headers = new Headers({
                  "Content-Type": "application/json",
                });
                const requestParam = {
                  method: "POST",
                  mode: "cors",
                  headers: headers,
                  cache: "no-cache",
                  redirect: "follow",
                  referrer: "no-referrer",
                  credentials: "include",
                  body: JSON.stringify({ ...values }),
                };
                try {
                  const response = await fetch(
                    `https://test.nexisltd.com/login`,
                    requestParam
                  );
                  console.log(response);
                  if (response.status === 200) {
                    console.log("User created successfully");
                    router.push("/attendanceTable");
                  } else {
                    console.log("Some error occured");
                  }
                } catch (err) {
                  console.log(err);
                }
              }}
            >
              <Form className="space-y-[40px]">
                <div className="secondary-heading capitalize flex justify-center py-[50px]">
                  Log in form
                </div>
                <div className="relative mx-auto flex justify-center w-full px-[20px] mobile:w-[320px] mobile:px-0 sm:w-[320px] md:w-[280px] lg:w-[320px]">
                  <Field
                    className=" w-full pl-[15px]"
                    id="email"
                    name="email"
                    placeholder="enter your email"
                    type="email"
                  />
                  <ErrorMessage
                    className="text-gray text-sm absolute bottom-[-20px] left-[10px] font-medium"
                    name="email"
                    component="div"
                  />
                </div>
                <div className="relative mx-auto flex justify-center w-full px-[20px] mobile:w-[320px] mobile:px-0 sm:w-[320px] md:w-[280px] lg:w-[320px]">
                  <Field
                    className=" w-full pl-[15px]"
                    id="password"
                    name="password"
                    placeholder="write your password"
                    type="password"
                  />
                  <ErrorMessage
                    className="text-gray text-sm absolute bottom-[-20px] left-[10px] font-medium"
                    name="password"
                    component="div"
                  />
                </div>
                <div className="mt-[30px] flex justify-center">
                  <button
                    className="primary-button capitalize shadow-[0px_4px_4px_rgba(0,0,0,0.25)]"
                    type="submit"
                  >
                    Log In
                  </button>
                </div>
                <div>
                  <div className="flex justify-center pt-[60px] pb-[30px] md:pb-0 text-sm font-medium text-gray">
                    Don't have an account?
                    <Link
                      className="uppercase text-md pl-[10px] text-blue underline font-semibold"
                      href="./signUp"
                    >
                      signup here
                    </Link>
                  </div>
                </div>
              </Form>
            </Formik>
          </div>
        </div>
      </div>
    </div>
  );
}
